export const GET_PROJECTS = "GET_PROJECTS";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const GET_PROJECT_BY_ID = "GET_PROJECT_BY_ID";
export const DELETE_PROJECT_BY_ID = "DELETE_PROJECT_BY_ID";
export const DUPLICATE_PROJECT_BY_ID = "DUPLICATE_PROJECT_BY_ID";
export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR";

export const GET_LAYOUTS = "GET_LAYOUTS";
export const CREATE_LAYOUT = "CREATE_LAYOUT";
export const GET_LAYOUT_BY_ID = "GET_LAYOUT_BY_ID";
export const DELETE_LAYOUT_BY_ID = "DELETE_LAYOUT_BY_ID";
export const DUPLICATE_LAYOUT_BY_ID = "DUPLICATE_LAYOUT_BY_ID";
export const CREATE_LAYOUT_ERROR = "CREATE_LAYOUT_ERROR";

export const GET_THEMES = "GET_THEMES";
export const CREATE_THEME = "CREATE_THEME";
export const GET_THEME_BY_ID = "GET_THEME_BY_ID";
export const DELETE_THEME_BY_ID = "DELETE_THEME_BY_ID";
export const DUPLICATE_THEME_BY_ID = "DUPLICATE_THEME_BY_ID";
export const CREATE_THEME_ERROR = "CREATE_THEME_ERROR";


export const GET_PRODUCTS = "GET_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const DELETE_PRODUCT_BY_ID = "DELETE_PRODUCT_BY_ID";
export const DUPLICATE_PRODUCT_BY_ID = "DUPLICATE_PRODUCT_BY_ID";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";







