export const GET_PROJECTS = "GET_PROJECTS";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const GET_PROJECT_BY_ID = "GET_PROJECT_BY_ID";
export const DELETE_PROJECT_BY_ID = "DELETE_PROJECT_BY_ID";
export const DUPLICATE_PROJECT_BY_ID = "DUPLICATE_PROJECT_BY_ID";
export const ADD_IMAGE_TO_PROJECT = "ADD_IMAGE_TO_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const MSG_PROJECTS = "MSG_PROJECTS";



export const GET_LAYOUTS = "GET_LAYOUTS";
export const CREATE_LAYOUT = "CREATE_LAYOUT";
export const GET_LAYOUT_BY_ID = "GET_LAYOUT_BY_ID";
export const DELETE_LAYOUT_BY_ID = "DELETE_LAYOUT_BY_ID";
export const DUPLICATE_LAYOUT_BY_ID = "DUPLICATE_LAYOUT_BY_ID";
export const MSG_LAYOUT = "MSG_LAYOUT";



export const GET_THEMES = "GET_THEMES";
export const CREATE_THEME = "CREATE_THEME";
export const GET_THEME_BY_ID = "GET_THEME_BY_ID";
export const DELETE_THEME_BY_ID = "DELETE_THEME_BY_ID";
export const DUPLICATE_THEME_BY_ID = "DUPLICATE_THEME_BY_ID";
export const MSG_THEMES = "MSG_THEMES";
export const ADD_COVER_BACKGROUND = "ADD_COVER_BACKGROUND";
export const ADD_IMAGE_COVER = "ADD_IMAGE_COVER";
export const LAYOUT_ID_FOR_THEME = "LAYOUT_ID_FOR_THEME";
export const FETCHED_LAYOUT = "FETCHED_LAYOUT";
export const LAYOUT_FOR_THEME = "LAYOUT_FOR_THEME";




export const GET_PRODUCTS = "GET_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const DELETE_PRODUCT_BY_ID = "DELETE_PRODUCT_BY_ID";
export const DUPLICATE_PRODUCT_BY_ID = "DUPLICATE_PRODUCT_BY_ID";
export const GET_LAYOUTS_FOR_PRODUCTS = "GET_LAYOUTS_FOR_PRODUCTS";
export const GET_THEMES_FOR_PRODUCTS = "GET_THEMES_FOR_PRODUCTS";
export const GET_PROJECTS_FOR_PRODUCTS = "GET_PROJECTS_FOR_PRODUCTS";
export const ADD_SLIDE_FOR_PRODUCT = "ADD_SLIDE_FOR_PRODUCT";
export const REMOVE_SLIDE_FOR_PRODUCT = "REMOVE_SLIDE_FOR_PRODUCT";
export const SET_CURRENT_ID_FOR_PROJECT = "SET_CURRENT_ID_FOR_PROJECT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const RETURNED_PRODUCT = "RETURNED_PRODUCT";
export const UPDATE_SLIDES = "UPDATE_SLIDES";
export const UPDATE_SLIDES_BACKGROUND = "UPDATE_SLIDES_BACKGROUND";

export const MSG_PRODUCTS = "MSG_PRODUCTS";












